### ISSUE TITLE
thaum crash

### ISSUE THREAD

**Issue by johnfg2610** [MyM-ModpackTeam/Civilization#23]
need to try and sort TE4 ores crashing when scanned out

**Comment by johnfg2610** [comment]
[crash-2016-03-17_13.24.46-client.txt](https://github.com/MyM-ModpackTeam/Civilization/files/179420/crash-2016-03-17_13.24.46-client.txt)
crash log relating to issue

**Comment by johnfg2610** [comment]
there appears to be nothing we can do about this on this version of mc I will close this as it is to my knowledge unfixable

**Comment by TheIcyOne** [comment]
Are all of the crash reports generated with 
`java.lang.StackOverflowError: Ticking entity
    at java.util.LinkedHashMap.afterNodeInsertion(Unknown Source)
    at java.util.HashMap.putVal(Unknown Source)
    at java.util.HashMap.put(Unknown Source)
    at thaumcraft.api.aspects.AspectList.add(AspectList.java:196)
    at thaumcraft.api.aspects.AspectList.copy(AspectList.java:36)`

or do the aspect numbers differ depending on the ores scanned?

**Comment by TheIcyOne** [comment]
https://github.com/CoFH/Feedback/issues/440
